# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.2-stretch
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: /go/src/github.com/Lookyan/netramesh
    steps:
      - checkout
      - setup_remote_docker
      - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run: docker build -t lookyan/netra-sidecar:$CIRCLE_BRANCH .
      - run: docker build -t -f Dockerfile-init lookyan/netra-init:$CIRCLE_BRANCH .
