apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: app
    spec:
      initContainers:
      - name: netra-init
        image: lookyan/netra-init:master
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 128Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
      containers:
      - name: app
        image: strm/helloworld-http
        ports:
        - containerPort: 80
      - command:
          - "bash"
          - "-c"
          - "./main --service-name ${POD_NAMESPACE}.$(echo ${POD_NAME} | sed -e 's/-[a-z0-9]*-[a-z0-9]*$//g')"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: JAEGER_AGENT_HOST
          value: "jaeger-agent"
        - name: JAEGER_AGENT_PORT
          value: "6831"
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
        image: lookyan/netra-sidecar:master
        imagePullPolicy: IfNotPresent
        name: netra-sidecar
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 3000Mi
        securityContext:
          privileged: true
          readOnlyRootFilesystem: false
          runAsUser: 1337

---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
